buckets:
  buildings:
    bucket_name: "s3-storage-classes-2025-3month-buildings"
    schema_file: "schemas/schema_bucket_buildings.json"
    keys_for_file_structure:
      - country
      - city
      - street_address
      - file_name
    log_file_name: "logs/building.log"
    log_level: "DEBUG"

  dogs:
    bucket_name: "s3-storage-classes-2025-3month-dogs"
    schema_file: "schemas/schema_bucket_dogs.json"
  person:
    bucket_name: "s3-storage-classes-2025-3month-person"
    schema_file: "schemas/schema_bucket_person.json"

